language: python
python:
- '3.4'
- nightly
script: python -m unittest tests/*.py
notifications:
  flowdock:
    secure: A8zGWUnV46Uc6v55z9JvMUUQ/H/931FPFQf98e91kvK2509OrbG23sKEhz2m4U6Ayz4gNu8Ows6aNan/OpKPQNzzD5zE/GKwIkoVjoZn3pnn6txdL0JtTo4rXWSrSY4pKzMIh+uBhdqijMLVPjWYs6EHuZcnTZawAje3w+QXeuhaO6X9NIz71S3QZXOCSA7I0iDZtuuq51rGo4ts5stR7a9ouKxSo/xMKj5Ng9oTYZjRtGC/Op9IV6OrfE9xsajZEWF3Q5cMXRhBUl9hJbtKY7HikmfI0cY+iXipK1N0030A7lBk/naoNkCvhxWhTOMnGBd0Vq1RxTbD7fUrN6MjKK4m3kGqkUxEWOGQn2ACQGvgzkYgH3ruu+nMWO7RT+SMhVeYTngSZ/++QtCy0KYMuaAmtuOLnUQPAviYVpfs3dzooOQunqOWEOrAsmHAZiOeXsSGh2IoKW+41z+NXGbF3tmwtewEo2ZzHHriqaNxE47QgfdrHE5vUptJVDcckaNvmL/YBht9gkYsARdRVVVIYNmMIaNFZBrmsDAAdypB/HIcI8opQtBAaFrVfBoLb4lQo2cWOG3hM8sIPevxga+1WfG7ZuXUSltHmti673GnO0zX0Qr8nHTWy3U5SCYHmzlrhICa1g9m6iB7MUQQBeLLTeUj1DwLiTr4QQd+x4/7kXs=
